apiVersion: v1
kind: Service
metadata:
  name: api-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: api-port
  selector:
    component: "api"
