apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    component: "api"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: "api"
    spec:
      containers:
      - name: api
        image: sample-api:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
        command: ["sh", "-c", "bundle exec rails server"]
